import { useState } from "react";
import { useSearchParams, useNavigate, useParams } from "react-router-dom";
import { useDebounce } from "@/hooks/useDebounce";
import { Search, FileText, Download, Eye } from "lucide-react";
import DataTable, { Column } from "@/components/DataTable";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatDate } from "@/utils/date";
import { useQuotations, useDownloadQuotation } from "@/hooks/useQuotations";
import { getStatusColor } from "../../leads/details/tabs/quotations/QuotationsTab";

interface UserQuotationsTabProps {
  userId: string;
}

const UserQuotationsTab = ({ userId }: UserQuotationsTabProps) => {
  const { companyId } = useParams();
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();
  const [search, setSearch] = useState(searchParams.get("search") || "");
  const debouncedSearch = useDebounce(search, 500);
  const [page, setPage] = useState(
    parseInt(searchParams.get("page") || "1", 10),
  );
  const [limit, setLimit] = useState(
    parseInt(searchParams.get("limit") || "10", 10),
  );

  const { data: quotationsData, isLoading } = useQuotations({
    user_id: userId,
    limit,
    offset: (page - 1) * limit,
    search: debouncedSearch || undefined,
  });

  const { mutate: download, isPending: isDownloading } = useDownloadQuotation();
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const quotations = quotationsData?.items || [];
  const serverTotal = quotationsData?.total || 0;

  const handleView = (item: any) => {
    navigate(`/${companyId}/leads/${item.lead_id}/quotations/${item.id}/view`);
  };

  const handleDownload = (item: any) => {
    setDownloadingId(item.id);
    download(
      {
        quotationId: item.id,
        quotationNumber: String(item.quotation_number),
      },
      {
        onSettled: () => setDownloadingId(null),
      },
    );
  };

  const columns: Column<any>[] = [
    {
      key: "quotation_number",
      header: "Quotation Details",
      render: (item) => (
        <div className="flex flex-col">
          <span
            onClick={() => handleView(item)}
            className="text-sm font-semibold text-primary hover:underline cursor-pointer decoration-primary/30 underline-offset-2"
          >
            {item.quotation_number}
          </span>
          <span className="text-[11px] text-muted-foreground">
            Created on {formatDate(item.created_at)}
          </span>
        </div>
      ),
    },
    {
      key: "lead_name",
      header: "Lead",
      render: (item) => (
        <div className="flex flex-col">
          <span className="text-sm font-medium text-foreground">
            {item.lead_name || "—"}
          </span>
          {item.company_name && (
            <span className="text-[11px] text-muted-foreground">
              {item.company_name}
            </span>
          )}
        </div>
      ),
    },
    {
      key: "grand_total",
      header: "Total",
      render: (item) => (
        <span className="text-sm font-bold text-foreground">
          ₹{(item.grand_total || 0).toLocaleString()}
        </span>
      ),
    },
    {
      key: "status",
      header: "Status",
      render: (item) => (
        <Badge
          variant="outline"
          className={`${getStatusColor(item.status)} text-[10px] px-2 py-0 h-5`}
        >
          {item.status}
        </Badge>
      ),
    },
    {
      key: "actions",
      header: "Actions",
      render: (item) => (
        <div className="flex items-center gap-1">
          <Button
            variant="ghost"
            size="icon"
            className="h-7 w-7 rounded-sm hover:bg-primary/10 hover:text-primary"
            onClick={() => handleDownload(item)}
            disabled={isDownloading && downloadingId === item.id}
          >
            <Download className="h-3.5 w-3.5" />
          </Button>
        </div>
      ),
    },
  ];

  return (
    <div className="w-full animate-fade-in rounded-lg border border-border/50 bg-card p-2 shadow-sm">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3 px-2">
        <div className="flex items-center gap-2">
          <div className="rounded-full bg-primary/10 p-2 text-primary">
            <FileText className="h-4 w-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-foreground">Quotations</h3>
            <p className="text-[11px] text-muted-foreground">
              View all quotations generated by this member
            </p>
          </div>
        </div>
        <div className="relative">
          <Search className="absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search quotations..."
            className="h-9 w-[240px] pl-9 text-sm"
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setPage(1);
            }}
          />
        </div>
      </div>
      <DataTable
        columns={columns}
        data={quotations}
        isLoading={isLoading}
        serverSide={true}
        serverPage={page}
        pageSize={limit}
        serverTotal={serverTotal}
        onServerPageChange={setPage}
        onServerPageSizeChange={(newSize) => {
          setLimit(newSize);
          setPage(1);
        }}
      />
    </div>
  );
};

export default UserQuotationsTab;
