import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import MeeshoNavbar from "@/components/navbar/MeeshoNavbar";
import { CartProvider } from "@/components/providers/CartProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <CartProvider>
            <MeeshoNavbar />
            {children}
          </CartProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
